// <auto-generated />
using System;
using System.Collections.Generic;
using Atlas.ControlPlane.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.ControlPlane.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260306012654_AddFeatures1245_ValueTracking_Automation_Templates_GitOps")]
    partial class AddFeatures1245_ValueTracking_Automation_Templates_GitOps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceRefs")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("agent_messages", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("ServiceGroupId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverRole")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("DecisionSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverridePayload")
                        .HasColumnType("text");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("approval_decisions", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EventPayload")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AutomationExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionLog")
                        .HasColumnType("text");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RollbackTriggered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("AutomationExecutions");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApprovalBypass")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImplementationSchedule")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxRiskThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinConfidenceThreshold")
                        .HasColumnType("numeric");

                    b.Property<bool>("RequiresAttestation")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerCriteria")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.BestPracticeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicabilityCriteria")
                        .HasColumnType("text");

                    b.Property<string>("ApplicabilityScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluationQuery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pillar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<string>("RemediationGuidance")
                        .HasColumnType("text");

                    b.Property<string>("RemediationIac")
                        .HasColumnType("text");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .IsUnique();

                    b.ToTable("best_practice_rules", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.BestPracticeViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriftCategory")
                        .HasColumnType("text");

                    b.Property<string>("DriftDetails")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("RuleId");

                    b.HasIndex("ServiceGroupId", "Status");

                    b.ToTable("best_practice_violations", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ComplianceAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssessmentSummary")
                        .HasColumnType("text");

                    b.Property<decimal>("CompliancePercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedRules")
                        .HasColumnType("integer");

                    b.Property<string>("FrameworkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrameworkVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric");

                    b.Property<int>("PassedRules")
                        .HasColumnType("integer");

                    b.Property<string>("PillarScores")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalRules")
                        .HasColumnType("integer");

                    b.Property<int>("WaivedRules")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("ComplianceAssessment");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoveredResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureResourceId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelemetryState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("discovered_resources", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("AnomalyCount")
                        .HasColumnType("integer");

                    b.Property<string>("CapturedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DependencyCount")
                        .HasColumnType("integer");

                    b.Property<string>("DependencyGraph")
                        .HasColumnType("text");

                    b.Property<string>("InventoryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ResourceCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceInventory")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlaContext")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelemetryHealth")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("discovery_snapshots", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DriftSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryBreakdown")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CriticalViolations")
                        .HasColumnType("integer");

                    b.Property<decimal>("DriftScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("HighViolations")
                        .HasColumnType("integer");

                    b.Property<int>("LowViolations")
                        .HasColumnType("integer");

                    b.Property<int>("MediumViolations")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalViolations")
                        .HasColumnType("integer");

                    b.Property<string>("TrendAnalysis")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId", "SnapshotTime");

                    b.ToTable("drift_snapshots", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.GitOpsPullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoMergeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CiCheckStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Labels")
                        .HasColumnType("text");

                    b.Property<string>("MergeCommitSha")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PullRequestUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reviewers")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangeSetId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("GitOpsPullRequests");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.IacChangeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("iac_change_sets", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeContext")
                        .HasColumnType("text");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("ConfidenceSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedImpact")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceReferences")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactedServices")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedChanges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("ReceivedApprovals")
                        .HasColumnType("smallint");

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<short>("RequiredApprovals")
                        .HasColumnType("smallint");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskProfile")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetEnvironment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TradeoffProfile")
                        .HasColumnType("text");

                    b.Property<string>("TriggerReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RecommendationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("RecommendationDecision");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RecommendationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicabilityCriteria")
                        .HasColumnType("text");

                    b.Property<decimal>("AverageSuccessRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedSavingsRange")
                        .HasColumnType("numeric");

                    b.Property<string>("IacTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParameterSchema")
                        .HasColumnType("text");

                    b.Property<string>("PostConditions")
                        .HasColumnType("text");

                    b.Property<string>("PreConditions")
                        .HasColumnType("text");

                    b.Property<string>("ProblemPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TypicalRiskScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RecommendationTemplates");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ReleaseAttestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttestationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("AttestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AttestedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ComponentVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IacChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("MockDetectionDetails")
                        .HasColumnType("text");

                    b.Property<string>("MockDetectionResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PromotionBlockReason")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ValidationMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ValidationPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("ValidationScopeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IacChangeSetId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("release_attestations", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RollbackPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IacChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text");

                    b.Property<string>("RollbackSteps")
                        .HasColumnType("text");

                    b.Property<string>("ValidationSteps")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IacChangeSetId")
                        .IsUnique();

                    b.ToTable("rollback_plans", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ScoreSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeltaFromPrevious")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResourceCount")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId", "Category", "RecordedAt");

                    b.ToTable("score_snapshots", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DomainType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Owners")
                        .HasColumnType("text");

                    b.Property<string>("Policies")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId", "DomainType");

                    b.ToTable("service_domains", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceDomainMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("DomainId", "NodeId")
                        .IsUnique();

                    b.ToTable("service_domain_memberships", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("ServiceGroupId", "SourceNodeId");

                    b.HasIndex("ServiceGroupId", "TargetNodeId");

                    b.ToTable("service_edges", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGraphSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainCount")
                        .HasColumnType("integer");

                    b.Property<int>("EdgeCount")
                        .HasColumnType("integer");

                    b.Property<string>("GraphMetrics")
                        .HasColumnType("text");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId", "SnapshotTime");

                    b.ToTable("service_graph_snapshots", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessOwner")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("HierarchyPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SloProfile")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.HasIndex("ParentServiceGroupId");

                    b.ToTable("service_groups", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroupHierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChildServiceGroupId");

                    b.HasIndex("ParentServiceGroupId", "ChildServiceGroupId", "RelationshipType")
                        .IsUnique();

                    b.ToTable("service_group_hierarchy", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroupScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceGroup")
                        .HasColumnType("text");

                    b.Property<string>("ScopeFilter")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("service_group_scopes", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureResourceId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlyCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("ReliabilityScore")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AzureResourceId");

                    b.HasIndex("ServiceGroupId", "NodeType");

                    b.ToTable("service_nodes", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.TemplateUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackNotes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParameterValues")
                        .HasColumnType("text");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateUsages");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeltaSummary")
                        .HasColumnType("text");

                    b.Property<string>("EventCategory")
                        .HasColumnType("text");

                    b.Property<string>("EventPayload")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("ScoreImpact")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("timeline_events", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ValueRealizationTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualImplementationCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ActualMonthlySavings")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ActualPaybackDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BaselineRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedImplementationCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedMonthlySavings")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EstimatedPaybackDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstMeasurementAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeasurementNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaybackAchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VarianceAnalysis")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeSetId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("ValueRealizations");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AgentMessage", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("Messages")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AnalysisRun", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceGroup");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("Approvals")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AutomationExecution", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AutomationRule", "AutomationRule")
                        .WithMany("Executions")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.BestPracticeViolation", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.BestPracticeRule", "Rule")
                        .WithMany("Violations")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("Violations")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("Rule");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ComplianceAssessment", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId");

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("ComplianceAssessments")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoveredResource", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", "Snapshot")
                        .WithMany("Resources")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId");

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("Snapshots")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DriftSnapshot", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("DriftSnapshots")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.GitOpsPullRequest", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.IacChangeSet", "ChangeSet")
                        .WithMany()
                        .HasForeignKey("ChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.IacChangeSet", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("ChangeSets")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RecommendationDecision", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("Decisions")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ReleaseAttestation", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.IacChangeSet", "ChangeSet")
                        .WithMany("Attestations")
                        .HasForeignKey("IacChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RollbackPlan", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.IacChangeSet", "ChangeSet")
                        .WithOne("RollbackPlan")
                        .HasForeignKey("Atlas.ControlPlane.Domain.Entities.RollbackPlan", "IacChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ScoreSnapshot", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceDomain", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceDomainMembership", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceDomain", "Domain")
                        .WithMany("Memberships")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceEdge", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceNode", "SourceNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceNode", "TargetNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceGroup");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGraphSnapshot", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroup", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ParentServiceGroup")
                        .WithMany("ChildServiceGroups")
                        .HasForeignKey("ParentServiceGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroupHierarchy", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ChildServiceGroup")
                        .WithMany("ParentRelationships")
                        .HasForeignKey("ChildServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ParentServiceGroup")
                        .WithMany("ChildRelationships")
                        .HasForeignKey("ParentServiceGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildServiceGroup");

                    b.Navigation("ParentServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroupScope", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("Scopes")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceNode", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.TemplateUsage", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.RecommendationTemplate", "Template")
                        .WithMany("Usages")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ValueRealizationTracking", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.IacChangeSet", "ChangeSet")
                        .WithMany()
                        .HasForeignKey("ChangeSetId");

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AnalysisRun", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AutomationRule", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.BestPracticeRule", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.IacChangeSet", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("RollbackPlan");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.Recommendation", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ChangeSets");

                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RecommendationTemplate", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceDomain", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroup", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("ChildRelationships");

                    b.Navigation("ChildServiceGroups");

                    b.Navigation("ComplianceAssessments");

                    b.Navigation("DriftSnapshots");

                    b.Navigation("ParentRelationships");

                    b.Navigation("Scopes");

                    b.Navigation("Snapshots");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });
#pragma warning restore 612, 618
        }
    }
}
