// <auto-generated />
using System;
using Atlas.ControlPlane.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.ControlPlane.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260214093030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceRefs")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("agent_messages", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("ServiceGroupId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverRole")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("DecisionSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverridePayload")
                        .HasColumnType("text");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("approval_decisions", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EventPayload")
                        .HasColumnType("text");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoveredResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureResourceId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelemetryState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("discovered_resources", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DependencyGraph")
                        .HasColumnType("text");

                    b.Property<string>("InventoryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlaContext")
                        .HasColumnType("text");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelemetryHealth")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("discovery_snapshots", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.IacChangeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("iac_change_sets", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceRefs")
                        .HasColumnType("text");

                    b.Property<string>("ImpactedServices")
                        .HasColumnType("text");

                    b.Property<short>("ReceivedApprovals")
                        .HasColumnType("smallint");

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("RequiredApprovals")
                        .HasColumnType("smallint");

                    b.Property<string>("RiskProfile")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetEnvironment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TradeoffProfile")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ReleaseAttestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttestationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("AttestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AttestedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IacChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("MockDetectionResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PromotionBlockReason")
                        .HasColumnType("text");

                    b.Property<string>("ValidationMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValidationScopeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IacChangeSetId");

                    b.ToTable("release_attestations", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RollbackPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IacChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text");

                    b.Property<string>("RollbackSteps")
                        .HasColumnType("text");

                    b.Property<string>("ValidationSteps")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IacChangeSetId")
                        .IsUnique();

                    b.ToTable("rollback_plans", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessOwner")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SloProfile")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.ToTable("service_groups", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroupScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceGroup")
                        .HasColumnType("text");

                    b.Property<string>("ScopeFilter")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("service_group_scopes", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventPayload")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ServiceGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ServiceGroupId");

                    b.ToTable("timeline_events", (string)null);
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AgentMessage", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("Messages")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AnalysisRun", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceGroup");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("Approvals")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoveredResource", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", "Snapshot")
                        .WithMany("Resources")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("Snapshots")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.IacChangeSet", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("ChangeSets")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ReleaseAttestation", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.IacChangeSet", "ChangeSet")
                        .WithMany("Attestations")
                        .HasForeignKey("IacChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.RollbackPlan", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.IacChangeSet", "ChangeSet")
                        .WithOne("RollbackPlan")
                        .HasForeignKey("Atlas.ControlPlane.Domain.Entities.RollbackPlan", "IacChangeSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeSet");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroupScope", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany("Scopes")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("Atlas.ControlPlane.Domain.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.ControlPlane.Domain.Entities.ServiceGroup", "ServiceGroup")
                        .WithMany()
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.AnalysisRun", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.DiscoverySnapshot", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.IacChangeSet", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("RollbackPlan");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.Recommendation", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ChangeSets");
                });

            modelBuilder.Entity("Atlas.ControlPlane.Domain.Entities.ServiceGroup", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("Scopes");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
